apiVersion: 3
dataDisplay:
  exampleSectionHtml: <code>letter 1:1001</code>
  textFormats:
    layout-orig-full: 
      method: layoutOrig
docs:
  docPage: about
  featureBase: 'https://github.com/{org}/{repo}/blob/master/docs/transcription{docExt}'
  featurePage: ''
interfaceDefaults:
  showGraphics: true
  showMath: true
  standardFeatures: false
  withLabels: true
provenanceSpec:
  corpus: Descartes = Descartes, all letters
  graphicsRelative: source/illustrations
  version: 1.0
  webBase: http://emlo-portal.bodleian.ox.ac.uk/collections/?catalogue=rene-descartes
  webHint: See how this corpus is included in the Bodleian catalog
  moduleSpecs:
  - corpus: Similar Sentences
    relative: parallels/tf
typeDisplay:
  volume:
    label: '{n}'
    template: 'vol. {n}'
  page:
    label: '{n}'
    template: 'p. {n}'
  letter:
    label: '{id} {date} from {sender} to {recipient}'
    template: '{id} {date} from {sender} to {recipient}'
    features: senderloc recipientloc
  p:
    label: '{n}'
  sentence:
    label: '{n}'
    condense: true
  figure:
    label: '{url}'
    graphics: true
  formula:
    label: '{notation}'
    features: tex
