apiVersion: 3
docs:
  docPage: about
  featureBase: 'https://github.com/{org}/{repo}/blob/master/docs/transcription{docExt}'
  featurePage: ''
interfaceDefaults:
  showGraphics: true
  showMath: true
provenanceSpec:
  corpus: Descartes = Descartes, all letters
  graphicsRelative: source/illustrations
  version: 0.9
  webBase: http://emlo-portal.bodleian.ox.ac.uk/collections/?catalogue=rene-descartes
  webHint: See how this corpus is included in the Bodleian catalog
typeDisplay:
  volume:
    featuresBare: n
  letter:
    featuresBare: id
  p:
    featuresBare: n
  figure:
    graphics: true
